weather:
  api:
    key: ${WEATHER_API_KEY}
    cities: Warszawa, Krakow, Lodz, Wroclaw, Poznan, Gdansk, Szczecin, Bydgoszcz, Lublin, Katowice, Bialystok, Gdynia, Czestochowa, Radom, Sosnowiec, Torun, Kielce, Gliwice, Zabrze, Bytom

spring:
  kafka:
    bootstrap-servers: ${BROKER_CONFIG:http://localhost:9092}
    producer:
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  fixed-rate: 5000 #ms
