spring:
  kafka:
    bootstrap-servers: ${BROKER_CONFIG:http://localhost:9092}
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
